services:
  - type: web
    plan: free
    name: neurospace
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn neurospace.backend.neurospace.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neurospace
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
