POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
    "username": "MonicaB",
    "password": "Password22!",
    "email": "test1@test.com",
    "bio" : "Monica is a test user",
}

###

POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "Beyonce",
    "password": "Password22!"
}

###
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 3a56feceffac32def184b80615c0e57af52a0dd2

{}

###
POST http://127.0.0.1:8000/logout
Content-Type: application/json
Authorization: Token 3a56feceffac32def184b80615c0e57af52a0dd2
{}

###
POST http://127.0.0.1:8000/UserProfile
Content-Type: application/json

    
    {
        
        "username" : "Test3",
        "bio": "I am a test user",
        "profile_pic": "https://www.google.com",
        
    }

###
GET http://127.0.0.1:8000/userprofile/test3/
Content-Type: application/json

{}

###
POST  http://127.0.0.1:8000/forum/
Content-Type: application/json
Authorization: Token fd47f4b0d5722f92eeff38024a4e12150391df16
    
  {
   "title" : "Timmy is ",
   "description" : "My best bro and my lucky charm",
   "user" : "36"
    }
###
GET http://127.0.0.1:8000/forum/
Content-Type: application/json
Authorization: Token 0815bb872fd7506b473a670eef9839af488b5cae

{}

###
POST http://127.0.0.1:8000/comment/
Content-Type: application/json
Authorization: Token 0815bb872fd7506b473a670eef9839af488b5cae
    
    {
        "content" : "I agree with you",
        "forum" : "15",
        "user" : "36"
    }

### 
GET http://127.0.0.1:8000/forum/search/?q=Timmy
Content-Type: application/json
Authorization: Token fd47f4b0d5722f92eeff38024a4e12150391df16

{}