POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
    "username": "Test3",
    "password": "Tester123",
    "email": "test3@test.com"
}
###

POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "Test3",
    "password": "Tester123"
}

###
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token ae9a24198db785e2314720d6ff38b6b72b5874d1

{}

###
POST http://127.0.0.1:8000/logout
Content-Type: application/json
Authorization: Token ae9a24198db785e2314720d6ff38b6b72b5874d1
  
{}

###
POST http://127.0.0:8000/127.0.0.1:8000/UserProfile
Content-Type: application/json
Authorization: Token ae9a24198db785e2314720d6ff38b6b72b5874d1
    
    {
        "user": 1,
        "username": "Test3",
        "bio": "I am a test user",
        "profile_pic": "https://www.google.com",
        
    }
