POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
    "username": "Test3",
    "password": "Tester123",
    "email": "test3@test.com"
}
###

POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "MichelleK",
    "password": "Password22!"
}

###
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 0d44b3b30abba119acc03839fb7bf76115185cdc

{}

###
POST http://127.0.0.1:8000/logout
Content-Type: application/json
Authorization: Token ae9a24198db785e2314720d6ff38b6b72b5874d1
  
{}

###
POST http://127.0.0.1:8000/UserProfile
Content-Type: application/json

    
    {
        
        "username" : "Test3",
        "bio": "I am a test user",
        "profile_pic": "https://www.google.com",
        
    }

###
GET http://127.0.0.1:8000/userprofile/test3/
Content-Type: application/json

{}

###
POST  http://127.0.0.1:8000/forum/
Content-Type: application/json
Authorization: Token 0815bb872fd7506b473a670eef9839af488b5cae
    
  {
   "title" : "Timmy is ",
   "description" : "My best bro and my lucky charm",
   "user" : "36"
    }
###
GET http://127.0.0.1:8000/forum/
Content-Type: application/json
Authorization: Token 0815bb872fd7506b473a670eef9839af488b5cae

{}

###
POST http://127.0.0.1:8000/comment/
Content-Type: application/json
Authorization: Token 0815bb872fd7506b473a670eef9839af488b5cae
    
    {
        "content" : "I agree with you",
        "forum" : "15",
        "user" : "36"
    }
