# Generated by Django 5.0.4 on 2024-04-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurospace', '0004_alter_like_user_alter_forum_user_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
