# Generated by Django 5.0.4 on 2024-04-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurospace', '0005_remove_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
