# Generated by Django 5.0.4 on 2024-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurospace', '0007_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='media/profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
