# Generated by Django 5.0.4 on 2024-04-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurospace', '0009_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='forum',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='forum',
        ),
    ]
