# Generated by Django 5.0.4 on 2024-04-23 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurospace', '0010_rename_post_comment_forum_rename_post_like_forum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='comments',
            field=models.ManyToManyField(related_name='comments', through='neurospace.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
